"""ElevenLabs music/SFX generation with durable local idempotency.

The adapter intentionally keeps generated bytes behind the private COS boundary and
never exposes request headers or provider URLs in its result contract.
"""

from __future__ import annotations

import hashlib
import json
import os
import socket
import sqlite3
import time
import urllib.error
import urllib.request
import uuid
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Callable, Iterator

from .. import ai_edit_v2_cos
from .base import (
    ProviderError,
    ProviderResult,
    RetryableProviderError,
    UnknownSubmissionError,
)


_MUSIC_MODEL = "music_v2"
_SFX_MODEL = "eleven_text_to_sound_v2"
_AUDIO_TYPES = frozenset({"audio/mpeg", "audio/mp3", "audio/wav", "audio/x-wav"})


class ElevenLabsProvider:
    """Generate one paid audio artifact at most once per idempotency key."""

    def __init__(
        self,
        *,
        owner: str,
        job_id: str,
        cos_api: Any = ai_edit_v2_cos,
        db_path: str,
        api_key: str | None = None,
        http_request: Callable[..., dict[str, Any]] | None = None,
        clock_ms: Callable[[], int] | None = None,
        timeout_seconds: int = 120,
        base_url: str | None = None,
    ) -> None:
        if not isinstance(owner, str) or not owner:
            raise ValueError("elevenlabs_job_scope_invalid")
        try:
            uuid.UUID(job_id)
        except (TypeError, ValueError) as exc:
            raise ValueError("elevenlabs_job_scope_invalid") from exc
        self.owner = owner
        self.job_id = job_id
        self.cos_api = cos_api
        self.db_path = str(db_path)
        self.api_key = api_key if api_key is not None else os.environ.get(
            "ELEVENLABS_API_KEY", ""
        )
        self.http_request = http_request or self._stdlib_request
        self.clock_ms = clock_ms or (lambda: round(time.monotonic() * 1000))
        self.timeout_seconds = int(timeout_seconds)
        self.base_url = (base_url or os.environ.get(
            "ELEVENLABS_BASE_URL", "https://api.elevenlabs.io"
        )).rstrip("/")
        self._initialize_store()

    def generate_music(
        self, prompt: str, duration_ms: int, idempotency_key: str
    ) -> ProviderResult:
        payload = {
            "prompt": self._clean_prompt(prompt),
            "music_length_ms": self._duration(duration_ms, 3_000, 600_000),
            "model_id": _MUSIC_MODEL,
            "force_instrumental": True,
        }
        return self._generate("music", "/v1/music", payload, idempotency_key)

    def generate_sfx(
        self, prompt: str, duration_ms: int, idempotency_key: str
    ) -> ProviderResult:
        duration = self._duration(duration_ms, 500, 30_000)
        payload = {
            "text": self._clean_prompt(prompt),
            "duration_seconds": duration / 1000,
            "model_id": _SFX_MODEL,
        }
        return self._generate("sfx", "/v1/sound-generation", payload, idempotency_key)

    @staticmethod
    def _clean_prompt(prompt: str) -> str:
        if not isinstance(prompt, str) or not prompt.strip():
            raise ProviderError("elevenlabs_prompt_invalid")
        return prompt.strip()

    @staticmethod
    def _duration(duration_ms: int, minimum: int, maximum: int) -> int:
        if (
            isinstance(duration_ms, bool)
            or not isinstance(duration_ms, int)
            or not minimum <= duration_ms <= maximum
        ):
            raise ProviderError("elevenlabs_duration_invalid")
        return duration_ms

    def _generate(
        self,
        capability: str,
        endpoint: str,
        payload: dict[str, Any],
        idempotency_key: str,
    ) -> ProviderResult:
        if not isinstance(idempotency_key, str) or not idempotency_key.strip():
            raise ProviderError("elevenlabs_idempotency_key_invalid")
        canonical_body = json.dumps(
            payload, ensure_ascii=False, sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
        digest = hashlib.sha256(
            capability.encode("utf-8") + b"\0" + canonical_body
        ).hexdigest()
        replay = self._reserve(idempotency_key, digest, capability)
        if replay is not None:
            return replay
        if not self.api_key:
            self._mark_terminal(idempotency_key, "elevenlabs_not_configured")
            raise ProviderError("elevenlabs_not_configured")

        headers = {
            "Accept": "audio/mpeg",
            "Content-Type": "application/json",
            "xi-api-key": self.api_key,
            "Idempotency-Key": idempotency_key,
        }
        started = self.clock_ms()
        try:
            response = self.http_request(
                "POST",
                self.base_url + endpoint,
                headers,
                canonical_body,
                self.timeout_seconds,
            )
        except urllib.error.HTTPError as exc:
            if 400 <= int(exc.code) < 500:
                error_code = "elevenlabs_request_rejected"
                self._mark_terminal(idempotency_key, error_code)
                raise ProviderError(error_code) from exc
            if 500 <= int(exc.code) < 600:
                error_code = "elevenlabs_http_retryable"
                self._mark_retryable(idempotency_key, error_code)
                raise RetryableProviderError(error_code) from exc
            else:
                error_code = "elevenlabs_http_error"
            self._mark_terminal(idempotency_key, error_code)
            raise ProviderError(error_code) from exc
        except Exception as exc:
            if self._definitely_not_submitted(exc):
                error_code = "elevenlabs_transport_retryable"
                self._mark_retryable(idempotency_key, error_code)
                raise RetryableProviderError(error_code) from exc
            # At this boundary we cannot prove whether the paid request crossed the
            # wire. Persist uncertainty and require reconciliation/manual recovery.
            self._mark_unknown(idempotency_key)
            raise UnknownSubmissionError("elevenlabs_submission_unknown") from exc

        elapsed_ms = max(0, self.clock_ms() - started)
        try:
            content = response.get("content", b"")
            if not isinstance(content, (bytes, bytearray)) or not content:
                raise ProviderError("elevenlabs_empty_output")
            content_type = str(response.get("content_type", "")).split(";", 1)[0].lower()
            if content_type not in _AUDIO_TYPES:
                raise ProviderError("elevenlabs_content_type_invalid")
            response_headers = {
                str(key).lower(): str(value)
                for key, value in dict(response.get("headers") or {}).items()
            }
            request_id = response_headers.get("request-id") or response_headers.get(
                "x-request-id", ""
            )
            provider_payload: dict[str, Any] = {}
            if capability == "sfx":
                character_cost = self._safe_nonnegative_int(
                    response_headers.get("character-cost")
                )
                if character_cost is None:
                    cost_units = 0
                    provider_payload["cost"] = {
                        "status": "unknown",
                        "unit": "characters",
                        "value": None,
                        "source": "provider_response_missing_character_cost",
                    }
                else:
                    cost_units = character_cost
                    provider_payload["cost"] = {
                        "status": "reported",
                        "unit": "characters",
                        "value": character_cost,
                        "source": "character-cost",
                    }
            else:
                cost_units = 0
                provider_payload["song_id"] = response_headers.get("song-id", "")
                provider_payload["cost"] = {
                    "status": "unknown",
                    "unit": "provider_units",
                    "value": None,
                    "source": "provider_response_missing_cost",
                }
            extension = ".wav" if "wav" in content_type else ".mp3"
            owner_scope = hashlib.sha256(self.owner.encode("utf-8")).hexdigest()[:16]
            key_scope = hashlib.sha256(idempotency_key.encode("utf-8")).hexdigest()[:24]
            cos_key = (
                f"ai-edit-v2/{owner_scope}/{self.job_id}/audio/"
                f"{capability}/{key_scope}{extension}"
            )
            self.cos_api.put_bytes(bytes(content), cos_key, content_type, private=True)
            metadata = self.cos_api.head_object(cos_key)
            if int(metadata.get("content_length", -1)) != len(content):
                raise ProviderError("elevenlabs_cos_verification_failed")
            stored_type = str(metadata.get("content_type", "")).split(";", 1)[0].lower()
            if stored_type != content_type:
                raise ProviderError("elevenlabs_cos_verification_failed")
            result = ProviderResult(
                provider="elevenlabs",
                capability=capability,
                request_id=request_id,
                payload={
                    "cos_key": cos_key,
                    "content_type": content_type,
                    "size_bytes": len(content),
                    "etag": str(metadata.get("etag", "")).strip('"'),
                    **provider_payload,
                },
                cost_units=cost_units,
                elapsed_ms=elapsed_ms,
            )
            self._complete(idempotency_key, result)
            return result
        except ProviderError as exc:
            self._mark_terminal(idempotency_key, str(exc))
            raise
        except Exception as exc:
            self._mark_terminal(idempotency_key, "elevenlabs_output_persistence_failed")
            raise ProviderError("elevenlabs_output_persistence_failed") from exc

    @staticmethod
    def _safe_nonnegative_int(value: str | None) -> int | None:
        try:
            parsed = int(value) if value is not None else -1
        except (TypeError, ValueError):
            return None
        return parsed if parsed >= 0 else None

    @staticmethod
    def _definitely_not_submitted(exc: BaseException) -> bool:
        reason = exc.reason if isinstance(exc, urllib.error.URLError) else exc
        if isinstance(reason, (socket.gaierror, ConnectionRefusedError)):
            return True
        if isinstance(reason, OSError):
            if getattr(reason, "winerror", None) in {10061, 11001}:
                return True
            safe_errnos = {
                value
                for value in (
                    getattr(socket, "EAI_AGAIN", None),
                    getattr(socket, "EAI_NONAME", None),
                )
                if value is not None
            }
            if getattr(reason, "errno", None) in safe_errnos:
                return True
        return False

    def _connect(self) -> sqlite3.Connection:
        Path(self.db_path).parent.mkdir(parents=True, exist_ok=True)
        connection = sqlite3.connect(self.db_path, timeout=10)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA busy_timeout=10000")
        return connection

    @contextmanager
    def _connection(self) -> Iterator[sqlite3.Connection]:
        connection = self._connect()
        try:
            with connection:
                yield connection
        finally:
            connection.close()

    def _initialize_store(self) -> None:
        deadline = time.monotonic() + 10
        while True:
            try:
                with self._connection() as connection:
                    mode = str(
                        connection.execute("PRAGMA journal_mode").fetchone()[0]
                    ).lower()
                    if mode != "wal":
                        mode = str(
                            connection.execute("PRAGMA journal_mode=WAL").fetchone()[0]
                        ).lower()
                    if mode != "wal":
                        raise sqlite3.OperationalError("failed to enable WAL journal mode")
                    connection.execute(
                        """CREATE TABLE IF NOT EXISTS edit_v2_audio_submissions(
                               owner TEXT NOT NULL,
                               job_id TEXT NOT NULL,
                               idempotency_key TEXT NOT NULL,
                               request_digest TEXT NOT NULL,
                               capability TEXT NOT NULL,
                               state TEXT NOT NULL,
                               result_json TEXT,
                               error_code TEXT,
                               PRIMARY KEY(owner,job_id,idempotency_key)
                           )"""
                    )
                return
            except sqlite3.OperationalError as exc:
                if "locked" not in str(exc).lower() or time.monotonic() >= deadline:
                    raise
                time.sleep(0.025)

    def _reserve(
        self, idempotency_key: str, request_digest: str, capability: str
    ) -> ProviderResult | None:
        with self._connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            row = connection.execute(
                """SELECT * FROM edit_v2_audio_submissions
                   WHERE owner=? AND job_id=? AND idempotency_key=?""",
                (self.owner, self.job_id, idempotency_key),
            ).fetchone()
            if row is None:
                connection.execute(
                    """INSERT INTO edit_v2_audio_submissions(
                           owner,job_id,idempotency_key,request_digest,capability,state
                       ) VALUES(?,?,?,?,?,'submitting')""",
                    (
                        self.owner,
                        self.job_id,
                        idempotency_key,
                        request_digest,
                        capability,
                    ),
                )
                connection.commit()
                return None
            if row["request_digest"] != request_digest or row["capability"] != capability:
                raise ProviderError("elevenlabs_request_conflict")
            if row["state"] == "completed":
                value = json.loads(row["result_json"])
                return ProviderResult(**value)
            if row["state"] == "retryable":
                changed = connection.execute(
                    """UPDATE edit_v2_audio_submissions
                       SET state='submitting',error_code=NULL
                       WHERE owner=? AND job_id=? AND idempotency_key=?
                         AND state='retryable'""",
                    (self.owner, self.job_id, idempotency_key),
                ).rowcount
                if changed != 1:
                    raise UnknownSubmissionError("elevenlabs_submission_unknown")
                connection.commit()
                return None
            if row["state"] == "terminal_failed":
                raise ProviderError(row["error_code"] or "elevenlabs_terminal_failure")
            raise UnknownSubmissionError("elevenlabs_submission_unknown")

    def _mark_unknown(self, idempotency_key: str) -> None:
        with self._connection() as connection:
            connection.execute(
                """UPDATE edit_v2_audio_submissions SET state='unknown_submission',
                       error_code='elevenlabs_submission_unknown'
                   WHERE owner=? AND job_id=? AND idempotency_key=? AND state='submitting'""",
                (self.owner, self.job_id, idempotency_key),
            )

    def _mark_retryable(self, idempotency_key: str, error_code: str) -> None:
        with self._connection() as connection:
            connection.execute(
                """UPDATE edit_v2_audio_submissions SET state='retryable',error_code=?
                   WHERE owner=? AND job_id=? AND idempotency_key=? AND state='submitting'""",
                (error_code, self.owner, self.job_id, idempotency_key),
            )

    def _mark_terminal(self, idempotency_key: str, error_code: str) -> None:
        with self._connection() as connection:
            connection.execute(
                """UPDATE edit_v2_audio_submissions SET state='terminal_failed',error_code=?
                   WHERE owner=? AND job_id=? AND idempotency_key=? AND state='submitting'""",
                (error_code, self.owner, self.job_id, idempotency_key),
            )

    def _complete(self, idempotency_key: str, result: ProviderResult) -> None:
        result_json = json.dumps(
            {
                "provider": result.provider,
                "capability": result.capability,
                "request_id": result.request_id,
                "payload": result.payload,
                "cost_units": result.cost_units,
                "elapsed_ms": result.elapsed_ms,
            },
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        )
        with self._connection() as connection:
            changed = connection.execute(
                """UPDATE edit_v2_audio_submissions SET state='completed',result_json=?,
                       error_code=NULL
                   WHERE owner=? AND job_id=? AND idempotency_key=? AND state='submitting'""",
                (result_json, self.owner, self.job_id, idempotency_key),
            ).rowcount
            if changed != 1:
                raise UnknownSubmissionError("elevenlabs_submission_unknown")

    @staticmethod
    def _stdlib_request(
        method: str,
        url: str,
        headers: dict[str, str],
        body: bytes,
        timeout: int,
    ) -> dict[str, Any]:
        request = urllib.request.Request(
            url=url, data=body, headers=headers, method=method
        )
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return {
                "content": response.read(),
                "content_type": response.headers.get_content_type(),
                "headers": dict(response.headers.items()),
            }
